---
- name: "unzip the artifact.tar.gz"
  become: true
  command: |
      tar –xvzf artifact.tar.gz –C .

- name: "Start the web server using the command"
  become: true
  command: |
      cd ~/backend
      npm install
      pm2 stop default
      pm2 start npm -- start