---
- name: "unzip the artifact.tar.gz"
  become: true
  unarchive:
    src: ~project/artifact.tar.gz
    dest: ./
    remote_src: yes


- name: "Start the web server using the command"
  become: true
  command: |
      npm install
      pm2 stop default
      pm2 start npm -- start