---
- name: "unzip the artifact.tar.gz"
  become: true
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: ./
    # remote_src: yes
# - name: "SetUp .env file"
#   become: true
#   file:
#     path: ~/.env
#     state: touch
#     mode: u+rw,g-wx,o-rwx
#     content: |
#       NODE_ENV=local
#       VERSION=1
#       TYPEORM_CONNECTION=postgres
#       TYPEORM_MIGRATIONS_DIR=./src/migrations
#       TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
#       TYPEORM_MIGRATIONS=./src/migrations/*.ts

#       TYPEORM_HOST=postgres.cndhbypnjuus.us-east-1.rds.amazonaws.com
#       TYPEORM_PORT=5432
#       TYPEORM_USERNAME=postgres
#       TYPEORM_PASSWORD=password
#       TYPEORM_DATABASE=postgres
- name: "copy .env to ec2 server"
  become: true
  copy:
    src: ~/project/backend/.env.sample
    dest: ./.env

- name: "Start the web server using the command"
  become: true
  command: pm2 start npm -- start