---
- name: "unzip the artifact.tar.gz"
  become: true
  file:
    path: ~/backend
    state: directory
    mode: 0775
  command: |
      tar –xvzf artifact.tar.gz –C ~/backend

- name: "Start the web server using the command "
  become: true
  command: |
      cd ~/backend
      npm install
      pm2 stop default
      pm2 start npm -- start