---
- name: "unzip the artifact"
  become: true
  command: |
      tar –xvzf artifact.tar.gz

- name: "Start the web server using the command"
  become: true
  command: |
      npm install
      pm2 stop default
      pm2 start npm -- start